# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-13 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190812_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='decs',
        ),
        migrations.AddField(
            model_name='post',
            name='desc',
            field=models.CharField(blank=True, max_length=1024, verbose_name='摘要'),
        ),
    ]
